# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{discover-unused-partials}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vinicius Baggio", "Willian Molinari (a.k.a PotHix)"]
  s.date = %q{2009-12-17}
  s.default_executable = %q{discover-unused-partials}
  s.description = %q{A script to help you finding out unused partials. Good for big projects or projects under heavy refactoring}
  s.email = %q{vinibaggio@gmail.com}
  s.executables = ["discover-unused-partials"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/discover-unused-partials",
     "discover-unused-partials.gemspec",
     "lib/discover-unused-partials.rb",
     "spec/discover-unused-partials_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/vinibaggio/discover-unused-partials}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Discover your unused partials}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/discover-unused-partials_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

